// <auto-generated />
using System;
using EmailTriageAgent.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailTriageAgent.Migrations
{
    [DbContext(typeof(EmailTriageDbContext))]
    partial class EmailTriageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmailTriageAgent.Domain.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.ModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SpamScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.HasIndex("ModelVersionId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Label")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ActiveModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BlockThreshold")
                        .HasColumnType("float");

                    b.Property<int>("GoldThreshold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastTrainedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewGoldSinceLastTrain")
                        .HasColumnType("int");

                    b.Property<bool>("RetrainEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("ReviewThreshold")
                        .HasColumnType("float");

                    b.Property<string>("SpamKeywordsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.Prediction", b =>
                {
                    b.HasOne("EmailTriageAgent.Domain.EmailMessage", "EmailMessage")
                        .WithOne("Prediction")
                        .HasForeignKey("EmailTriageAgent.Domain.Prediction", "EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmailTriageAgent.Domain.ModelVersion", "ModelVersion")
                        .WithMany()
                        .HasForeignKey("ModelVersionId");

                    b.Navigation("EmailMessage");

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.Review", b =>
                {
                    b.HasOne("EmailTriageAgent.Domain.EmailMessage", "EmailMessage")
                        .WithMany("Reviews")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("EmailTriageAgent.Domain.EmailMessage", b =>
                {
                    b.Navigation("Prediction");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
